<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   <title>Attendance Report</title>
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        body{
            font-size: 12px;
        }
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        .collapse-table td, .collapse-table th{
            padding:5px;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0; font-size:22px;">{{ auth()->user()->organization->name }}</h3>
            <p style="margin:0; font-size:16px;">FOUNDER: {{ auth()->user()->organization->founder }}</p>
            <hr>
        <p style="margin:0; text-decoration:underline; font-size:16px;">Date wise attendance report - {{ $date }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <table width="100%" >
            <tr>
                <td width="50%">
                Report generated by: {{ auth()->user()->name }} Date : {{ date('Y/m/d H:i A') }}
                </td>
                <td style="text-align:right" width="50%">
                    Smart attendance management system, Developed by: KYAMCH IT
                </td>
            </tr>
        </table>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
        <table class="collapse-table">
            <thead>
                
                <tr>
                    <th rowspan=2 width="50px">SL</th>
                    <th rowspan=2 >NAME</th>
                    <th rowspan=2 width="120px">EMPLOYEE ID</th>
                    <th rowspan=2 width="60px">STATUS</th>
                    <th colspan=2 width="140px">SCHEDULE</th>
                    <!-- <th >END</th> -->
                    <th colspan=2 width="140px">ATTENDANCE</th>
                    <th colspan=3 width="210px">LUNCH OUT/IN</th>
                    <!-- <th >DUTY OUT</th> -->
                    <th colspan=2 width="140px">LATE IN / EARLY LEAVE</th>
                    <!-- <th >EARLY LEAVE</th> -->
                </tr>
                <tr>
                    <!-- <th width="50px" >SL</th> -->
                    <!-- <th>NAME</th> -->
                    <!-- <th >EMPLOYEE ID</th> -->
                    <!-- <th >STATUS</th> -->
                    <th  width="70px">START</th>
                    <th width="70px">END</th>
                    <th width="70px">IN</th>
                    <th width="70px">OUT</th>
                    <th width="70px">OUT</th>
                    <th width="70px">IN</th>
                    <th width="70px">SPEND</th>
                    <th width="70px">LI</th>
                    <th width="70px">EL</th>
                </tr>


            </thead>
            <tbody>
                @foreach($attendances as $attendance)
                    @if($attendance->is_day_off)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $attendance->employee->name }}</td>
                            <td>{{ $attendance->employee->employment_id }}</td>
                            <td style="color:green">Day off</td>
                            <td colspan="9" style="text-align:center" >Weekly holyday</td>
                        </tr>
                    @else
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $attendance->employee->name }}</td>
                            <td>{{ $attendance->employee->employment_id }}</td>
                            <td style="color:{{ $attendance->is_present? '': 'red' }};">{{ $attendance->is_present? "Present": "Absent" }}</td>
                            <td>{{ \Carbon\Carbon::parse($attendance->schedule_in)->format('h:i A') }}</td>
                            <td>{{ \Carbon\Carbon::parse($attendance->schedule_out)->format('h:i A') }}</td>
                            <td>{{ $attendance->in_time? \Carbon\Carbon::parse($attendance->in_time)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->out_time? \Carbon\Carbon::parse($attendance->out_time)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->lunch_out? \Carbon\Carbon::parse($attendance->lunch_out)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->lunch_in? \Carbon\Carbon::parse($attendance->lunch_out)->format('h:i A') : '' }}</td>
                            <td>
                                @php
                                    if($attendance->lunch_out && $attendance->lunch_in){
                                        $lunch_out = \Carbon\Carbon::parse($attendance->lunch_out);
                                        $lunch_in = \Carbon\Carbon::parse($attendance->lunch_in);

                                        $timeDifference = $lunch_out->diff($lunch_in);
                                        echo $timeDifference->format('%H h %I m');
                                    }

                                @endphp
                            </td>
                            <td>
                                @php
                                    $scheduleIn = \Carbon\Carbon::parse($attendance->schedule_in);
                                    $scheduleInWithFlexTime = \Carbon\Carbon::parse($attendance->schedule_in)->addMinutes(auth()->user()->organization->flex_time);
                                    $inTime = \Carbon\Carbon::parse($attendance->in_time);

                                    if ($attendance->in_time && $inTime->gt($scheduleInWithFlexTime)) {
                                        $timeDifference = $inTime->diff($scheduleIn);
                                        echo $timeDifference->format('%H h %I m');
                                    }
                                @endphp
                            </td>
                            <td>
                                @php
                                    $scheduleOut = \Carbon\Carbon::parse($attendance->schedule_out);
                                    $outTime = \Carbon\Carbon::parse($attendance->out_time);
                                    $outTimeWithFlexTime = \Carbon\Carbon::parse($attendance->out_time)->addMinutes(auth()->user()->organization->flex_time);
                        
                                    if ($attendance->out_time && $scheduleOut->gt($outTimeWithFlexTime)) {
                                        $timeDifference = $scheduleOut->diff($outTime);
                                        echo $timeDifference->format('%H h %I m');
                                    }
                                @endphp
                            </td>
                        </tr>
                    @endif
                    
                @endforeach
            </tbody>
        </table>
    </main>

</body>


</html>