<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   <title>Attendance Report</title>
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        /* body{
            font-family:'nikosh_bangla', sans-serif;
        } */
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        td, th{
            padding:5px;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0">{{ auth()->user()->organization->name }}</h3>
            <p style="margin:0">FOUNDER: DR. M. M. AMJAD HUSSAIN</p>
            <hr>
        <p style="margin:0; text-decoration:underline;">Daily attendance report - {{ $reports_date }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <p style="text-align:center;">Report generated by - {{ auth()->user()->name }}. Time : {{ date('Y/m/d H:i A') }}</p> <br>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
        <table class="collapse-table">
            <tr>
                <th width="20px" >SL</th>
                <th width="25%" >NAME</th>
                <th width="15%" >EMPLOYEE ID</th>
                <th width="12%" >STATUS</th>
                <th width="12%" >DUTY IN</th>
                <th width="12%" >DUTY OUT</th>
                <th width="12%" >LATE IN</th>
                <th width="12%" >EARLY LEAVE</th>
            </tr>
            @foreach($daily_attendances as $attendance)
                @if($attendance->is_day_off)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $attendance->employee->name }}</td>
                        <td>{{ $attendance->employee->employment_id }}</td>
                        <td style="color:green">"Day off"</td>
                        <td colspan="4" >Weekly holyday</td>
                    </tr>
                @else
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $attendance->employee->name }}</td>
                        <td>{{ $attendance->employee->employment_id }}</td>
                        <td style="color:{{ $attendance->is_present? '#000': 'red' }};">{{ $attendance->is_present? "Present": "Absent" }}</td>
                        <td>{{ $attendance->in_time }}</td>
                        <td>{{ $attendance->out_time }}</td>
                        <td>{{ $attendance->schedule_in }}</td>
                        <td>{{ $attendance->schedule_out }}</td>
                    </tr>
                @endif
                
            @endforeach
        </table>
    </main>

</body>


</html>