<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        /* body{
            font-family:'nikosh_bangla', sans-serif;
        } */
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        td, th{
            padding:5px;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0">{{ auth()->user()->organization->name }}</h3>
            <p style="margin:0">FOUNDER: DR. M. M. AMJAD HUSSAIN</p>
            <hr>
        <p style="margin:0; text-decoration:underline;">Daily attendance report - {{ $reports_date }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <p style="text-align:center;">Report generated by - {{ auth()->user()->name }}. Time : {{ date('Y/m/d H:i A') }}</p> <br>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
        <table class="collapse-table">
            <tr>
                <th width="20px" >SL</th>
                <th width="25%" >NAME</th>
                <th width="15%" >EMPLOYEE ID</th>
                <th width="12%" >STATUS</th>
                <th width="12%" >DUTY IN</th>
                <th width="12%" >DUTY OUT</th>
                <th width="12%" >LATE IN</th>
                <th width="12%" >EARLY LEAVE</th>
            </tr>
            @foreach($employees as $employee)
                @php
                    if(count($employee->dateWiseAttendance)){
                        $attendance = $employee->dateWiseAttendance[0];
                    }else{
                        $attendance = (object) [
                                'attendance_status' => false,
                                'entry_time' => false,
                                'exit_time' => false,
                                'late_entry_time' => false,
                                'erly_exit_time' => false,
                            ];
                    }
                @endphp
               
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $employee->name }}</td>
                    <td>{{ $employee->employment_id }}</td>
                    <td style="color:{{ $attendance->attendance_status? '#000': 'red' }};">{{ $attendance->attendance_status? "Present": "Absent" }}</td>
                    <td>{{ $attendance->entry_time }}</td>
                    <td>{{ $attendance->exit_time }}</td>
                    <td>{{ $attendance->late_entry_time }}</td>
                    <td>{{ $attendance->erly_exit_time }}</td>
                </tr>
            @endforeach
        </table>
    </main>

</body>


</html>