
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        body{
            font-size: 12px;
        }
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        .collapse-table td, .collapse-table th{
            padding:5px;
            text-align:left;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0; font-size:22px;">{{ auth()->user()->organization->name }}</h3>
            <p style="margin:0; font-size:16px;">FOUNDER: {{ auth()->user()->organization->founder }}</p>
            <hr>
        <p style="margin:0; text-decoration:underline; font-size:16px;">Monthly attendance report - {{ $date }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <table width="100%" >
            <tr>
                <td width="50%">
                Report generated by: {{ auth()->user()->name }} Date : {{ date('Y/m/d H:i A') }}
                </td>
                <td style="text-align:right" width="50%">
                    Smart attendance management system, Developed by: KYAMCH IT
                </td>
            </tr>
        </table>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
    

    @foreach($employees as $employee)
        @php 
            $j = 0;
            $day_off_count = 0;
            $working_day_count = 0;
            $present_count = 0;
            $absent_count = 0;
            $late_in_count = 0;
            $early_out_count = 0;
        @endphp
        <h3>{{ ++$i.'. '.$employee->employment_id }} - {{ $employee->name }} - {{ $employee->designation }} </h3>
        <table class="collapse-table" >
            <thead>
                <tr>
                    <th rowspan=2  width="50px">SL</th>
                    <th rowspan=2 >DATE</th>
                    <th rowspan=2 >STATUS</th>
                    <th colspan=2 width="160px">SCHEDULE</th>
                    <!-- <th >END</th> -->
                    <th colspan=2 width="160px">ATTENDANCE</th>
                    <th colspan=3 width="160px">LUNCH OUT/IN</th>
                    <!-- <th >DUTY OUT</th> -->
                    <th colspan=2 width="160px">LATE IN / EARLY LEAVE</th>
                    <!-- <th >EARLY LEAVE</th> -->
                </tr>
                <tr>
                    <!-- <th width="50px" >SL</th> -->
                    <!-- <th >STATUS</th> -->
                    <th width="80px">START</th>
                    <th width="80px">END</th>
                    <th width="80px">IN</th>
                    <th width="80px">OUT</th>
                    <th width="80px">OUT</th>
                    <th width="80px">IN</th>
                    <th width="80px">SPEND</th>
                    <th width="80px">LI</th>
                    <th width="80px">EL</th>
                </tr>
            </thead>

            @foreach($employee->daily_attendances as $attendance)
                    @if($attendance->is_day_off)
                        @php 
                            ++$day_off_count; 
                        @endphp
                        <tr>
                            <td>{{ ++$j }}</td>
                            <td>{{ $attendance->date }}</td>
                            <td style="color:green">Day off</td>
                            <td colspan="6" style="text-align:center" >Weekly holyday</td>
                        </tr>
                    @else
                        @php 
                            ++$working_day_count; 
                            $present_count +=$attendance->is_present;
                            $absent_count +=!$attendance->is_present;
                        @endphp
                        <tr>
                            <td>{{ ++$j }}</td>
                            <td>{{ $attendance->date }}</td>
                            <td style="color:{{ $attendance->is_present? '': 'red' }};">{{ $attendance->is_present? "Present": "Absent" }}</td>
                            <td>{{ \Carbon\Carbon::parse($attendance->schedule_in)->format('h:i A') }}</td>
                            <td>{{ \Carbon\Carbon::parse($attendance->schedule_out)->format('h:i A') }}</td>
                            <td>{{ $attendance->in_time? \Carbon\Carbon::parse($attendance->in_time)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->out_time? \Carbon\Carbon::parse($attendance->out_time)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->lunch_out? \Carbon\Carbon::parse($attendance->lunch_out)->format('h:i A') : '' }}</td>
                            <td>{{ $attendance->lunch_in? \Carbon\Carbon::parse($attendance->lunch_out)->format('h:i A') : '' }}</td>
                            <td>
                                @php
                                    if($attendance->lunch_out && $attendance->lunch_in){
                                        $lunch_out = \Carbon\Carbon::parse($attendance->lunch_out);
                                        $lunch_in = \Carbon\Carbon::parse($attendance->lunch_in);

                                        $timeDifference = $lunch_out->diff($lunch_in);
                                        echo $timeDifference->format('%H h %I m');
                                    }

                                @endphp
                            </td>
                            <td>
                                @php
                                    $scheduleIn = \Carbon\Carbon::parse($attendance->schedule_in);
                                    $scheduleInWithFlexTime = \Carbon\Carbon::parse($attendance->schedule_in)->addMinutes(auth()->user()->organization->flex_time);
                                    $inTime = \Carbon\Carbon::parse($attendance->in_time);

                                    if ($attendance->in_time && $inTime->gt($scheduleInWithFlexTime)) {
                                        ++$late_in_count;
                                        $timeDifference = $inTime->diff($scheduleIn);
                                        echo $timeDifference->format('%H h %I m');
                                    }
                                @endphp
                            </td>
                            <td>
                                @php
                                    $scheduleOut = \Carbon\Carbon::parse($attendance->schedule_out);
                                    $outTime = \Carbon\Carbon::parse($attendance->out_time);
                                    $outTimeWithFlexTime = \Carbon\Carbon::parse($attendance->out_time)->addMinutes(auth()->user()->organization->flex_time);
                        
                                    if ($attendance->out_time && $scheduleOut->gt($outTimeWithFlexTime)) {
                                        ++$early_out_count;
                                        $timeDifference = $scheduleOut->diff($outTime);
                                        echo $timeDifference->format('%H h %I m');
                                    }
                                @endphp
                            </td>
                        </tr>
                    @endif
                    
                @endforeach
                <tr>
                    <td colspan=12>Total: {{$j}} days, Day off: {{$day_off_count}} days, Working day: {{$working_day_count}} days, Present: {{$present_count}} days, Absent: {{$absent_count}} days, Late in: {{$late_in_count}} days, Early leave: {{$early_out_count}} days,</td>
                </tr>
            
        </table>
        <br>
    @endforeach
    </main>

</body>


</html>