<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        body{
            font-size: 12px;
        }
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        td, th{
            padding:5px;
            text-align:left;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0">{{ auth()->user()->organization->name }}</h3>
            <p style="margin:0">FOUNDER: DR. M. M. AMJAD HUSSAIN</p>
            <hr>
        <p style="margin:0; text-decoration:underline;">Monthly attendance report - {{ $reports_date }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <p style="text-align:center;">Report generated by - {{ auth()->user()->name }}. Time : {{ date('Y/m/d H:i A') }}</p> <br>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
    

    @foreach($employees as $employee)
        @php 
            $j = 0;
        @endphp
        <h3>{{ ++$i.'. '.$employee->name }} <span> ({{ $employee->schedule_start_time }} - {{ $employee->schedule_end_time }})</span> </h3>
        <table class="collapse-table" >
            <tr>
                <th width="30px" >SL</th>
                <th>DATE </th>
                <th width="15%" >STATUS</th>
                <th width="15%" >DUTY IN</th>
                <th width="15%" >DUTY OUT</th>
                <th width="15%" >LATE IN</th>
                <th width="15%" >EARLY LEAVE</th>
            </tr>
            @foreach($employee->dateWiseAttendance as $attendance)
            <tr>
                <td>{{ ++$j }}</td>
                <td>{{ $attendance->date }}</td>
                <td style="color:{{ $attendance->attendance_status? '#000': 'red' }};">{{ $attendance->attendance_status? "Present": "Absent" }}</td>
                <td>{{ $attendance->entry_time }}</td>
                <td>{{ $attendance->exit_time }}</td>
                <td>{{ $attendance->late_entry_time }}</td>
                <td>{{ $attendance->erly_exit_time }}</td>
            </tr>
            @endforeach
            <tr>
                <th colspan=5 >Total attendances : {{ $j }} days</th>
                <th >{{ $employee->laet_entry_count }} days</th>
                <th >{{ $employee->erly_exit_count }} days</th>
            </tr>
        </table>
        <br>
    @endforeach
    </main>

</body>


</html>