
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   
    <style>
        @page {
            margin: 150px 100px;
            font-size:12px;
        }

        header {
            position: fixed;
            top: -100px;
            left: 0px;
            right: 0px;
            height: 100px;
        }

        footer {
            position: fixed; 
            bottom: -120px; 
            left: 0px; 
            right: 0px;
            height: 50px; 
        }

        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        .collapse-table td, .collapse-table th{
            padding:5px;
            text-align:left;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
        <header>
            <div style="text-align:center;">
                <h3 style="margin:0; font-size:22px;">{{ auth()->user()->shop->name }}</h3>
                <hr>
                <p style="margin:0; text-decoration:underline; font-size:16px;">{{$report_title}} </p>
            </div>
        </header>

        <footer>
            <table width="100%" >
                <tr>
                    <td width="50%">
                    Generated by: {{ auth()->user()->name }} Date : {{ date('Y/m/d h:i A') }}
                    </td>
                    <td style="text-align:right" width="50%">
                        Point of sale, Developed by: KYAMCH IT
                    </td>
                </tr>
            </table>
        </footer>



    <main style="word-wrap: break-word;">
    
    @if($purchases->isEmpty())
        <table class="collapse-table">
            <tr>
                <th>No dta found !</th>
            </tr>
        </table>
    @else
        <table class="collapse-table" >
            <thead>
                <tr>
                    <th>SL</th>
                    <th>DATE</th>
                    <th>PRODUCT ID</th>
                    <th>PRODUCT NAME</th>
                    <th>RATE</th>
                    <th>QTY</th>
                    <th>PRICE</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $total_purchase = 0;
                @endphp
                @foreach($purchases as $row)
                    @php
                        $total_purchase += $row->total_price;
                    @endphp
                    <tr>
                        <td>{{++$i}}</td>
                        <td>{{ \Carbon\Carbon::parse($row->created_at)->format('d-m-Y') }}</td>
                        <td>{{ $row->product->sku }}</td>
                        <td>{{ $row->product->name }}</td>
                        <td>{{ $row->unit_price }}</td>
                        <td>{{ $row->quantity }}</td>
                        <td>{{ $row->total_price }}</td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="6">Total purchase amount</td>
                    <td>{{ number_format($total_purchase, 2) }}</td>
                </tr>
            </tbody>
        </table>
    @endif
    </main>

</body>


</html>