
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
   
    <style>
        @page {
            margin: 150px 100px;
            font-size:12px;
        }

        header {
            position: fixed;
            top: -100px;
            left: 0px;
            right: 0px;
            height: 100px;
        }

        footer {
            position: fixed; 
            bottom: -120px; 
            left: 0px; 
            right: 0px;
            height: 50px; 
        }

        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        .collapse-table td, .collapse-table th{
            padding:5px;
            text-align:left;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
        <header>
            <div style="text-align:center;">
                <h3 style="margin:0; font-size:22px;">{{ auth()->user()->shop->name }}</h3>
                <hr>
                <p style="margin:0; text-decoration:underline; font-size:16px;">{{$report_title}} </p>
            </div>
        </header>

        <footer>
            <table width="100%" >
                <tr>
                    <td width="50%">
                    Generated by: {{ auth()->user()->name }} Date : {{ date('Y/m/d h:i A') }}
                    </td>
                    <td style="text-align:right" width="50%">
                        Point of sale, Developed by: KYAMCH IT
                    </td>
                </tr>
            </table>
        </footer>



    <main style="word-wrap: break-word;">
    @if($invoices->isEmpty())
        <table class="collapse-table">
            <tr>
                <th>No dta found !</th>
            </tr>
        </table>
    @else
        @foreach($invoices as $user_name => $sells)
            @php
                $j = 0;
                $total_sell = 0;
                $total_paid = 0;
            @endphp
            <table class="collapse-table" >
                <thead>
                    <tr>
                        <th colspan="6">{{ ++$i }} . {{ $user_name }}</th>
                    </tr>
                    <tr>
                        <th>SL</th>
                        <th>DATE</th>
                        <th>INVOICE ID</th>
                        <th>BILL</th>
                        <th>PAID</th>
                        <th>DUE</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($sells as $invoice)
                        @php
                            $total_sell += $invoice->total;
                            $total_paid += $invoice->paid_amount;
                        @endphp
                        <tr>
                            <td>{{ ++$j }}</td>
                            <td>{{ \Carbon\Carbon::parse($invoice->created_at)->format('d-m-Y') }}</td>
                            <td>{{ $invoice->invoice_uid }}</td>
                            <td>{{ $invoice->total }}</td>
                            <td>{{ $invoice->paid_amount }}</td>
                            <td>{{ $invoice->total -  $invoice->paid_amount}}</td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="3" >Total</td>
                        <td>{{ $total_sell }}</td>
                        <td>{{ $total_paid }}</td>
                        <td>{{ $total_sell - $total_paid }}</td>
                    </tr>
                </tbody>
            </table>
        @endforeach
    @endif
    </main>

</body>


</html>